export interface ClassData {
  class: string
  room: string
  level: string
  cohort: string
  shift: string
  englishInstructor: string
  senior: string
}

export const classData: ClassData[] = [
  {
    class: "Fnd-01",
    room: "G04",
    level: "Intermediate",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Mohamed Hashim Mohamed Ali",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-02",
    room: "G06",
    level: "Intermediate",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Mohamed Dol",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-03",
    room: "G07",
    level: "Intermediate",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Ameen Daniel",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-04",
    room: "G09",
    level: "Intermediate",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Abdul Raqib Choudhury",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-05",
    room: "G10",
    level: "Intermediate",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Hamid Hashim",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-06",
    room: "G14",
    level: "Intermediate",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Brahim Dafiri",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-07",
    room: "G16",
    level: "PI-S2",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Makhtar Hussien Aidid",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-08",
    room: "F04",
    level: "PI-S2",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Farah Egal",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-09",
    room: "F05",
    level: "PI-S2",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Murshad Twaibu Bonomali",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-10",
    room: "F06",
    level: "PI-S2",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Shaheen Mangal",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-11",
    room: "F07",
    level: "PI-S2",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Abdirahman Hassan Mohamed",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-12",
    room: "F08",
    level: "PI-S2",
    cohort: "23",
    shift: "AM",
    englishInstructor: "Razeehn Achmad",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-13",
    room: "F09",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Issa Mckey",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-14",
    room: "F11",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Yaquob Ali",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-15",
    room: "F12",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mohammed Ashif Uddin",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-16",
    room: "F13",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mohamed Ibrahim Elmi",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-17",
    room: "F16",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mohammed Barreh",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-18",
    room: "F17",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Imran Mohamed Osman",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-19",
    room: "F19",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mahmoud Idris Sunabara",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-20",
    room: "F21",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Yusuf Farhan Hassan",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-21",
    room: "F24",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mohamed Nur Nafei Omar",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-22",
    room: "F26",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Samer Abdulwahab Jahar",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-23",
    room: "F27",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Dayib Maalim Abdullahi",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-24",
    room: "F28",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Muhammad Jawwaad Akleker",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-25",
    room: "F33",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Matloob Hussain",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-26",
    room: "F34",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mohamed Ahmed Awil",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-27",
    room: "F35",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Nassar Muhammad Yousaf",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-28",
    room: "F36",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Shabier Begg",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-29",
    room: "F37",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Abdul Wahid Hashi Musa",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-30",
    room: "F38",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mohammed Ali Hussain",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-31",
    room: "F39",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Fahad Ahmed Pereira",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-32",
    room: "F40",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Sean Scott",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-33",
    room: "S04",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Musab Abdullah",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-34",
    room: "S06",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Faisal Mahmood",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-35",
    room: "S08",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Osman Idris Mohamed",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-36",
    room: "S10",
    level: "Repeater",
    cohort: "21",
    shift: "AM",
    englishInstructor: "Raja Jahangeer Khan",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-37",
    room: "S13",
    level: "Repeater",
    cohort: "21",
    shift: "AM",
    englishInstructor: "Mohammed Qasim Shahid",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-38",
    room: "S45",
    level: "Elementary A0",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Munir Said Oumar",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-39",
    room: "S32",
    level: "Elementary A0",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mohammed Shakeeb Anwar",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-40",
    room: "S34",
    level: "Elementary",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Saeed Jama Farah",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-41",
    room: "S38",
    level: "Elementary A0",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Ali Osman",
    senior: "Haroon Raja",
  },
  {
    class: "Fnd-42",
    room: "S40",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Mohamoud Hurreh",
    senior: "Sheraz Siddiq",
  },
  {
    class: "Fnd-43",
    room: "S42",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Abdullah Hassan Noor Roble",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-44",
    room: "S44",
    level: "Intermediate",
    cohort: "24",
    shift: "AM",
    englishInstructor: "Ahmed Ali Haibe Mohamoud",
    senior: "Sajaad Younis",
  },
  {
    class: "Fnd-45",
    room: "F37",
    level: "Repeater",
    cohort: "21",
    shift: "PM",
    englishInstructor: "Mogamat Rashaad Toffa",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-46",
    room: "F04",
    level: "Intermediate",
    cohort: "23",
    shift: "PM",
    englishInstructor: "Joseph James Killeen",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-47",
    room: "F05",
    level: "Intermediate",
    cohort: "23",
    shift: "PM",
    englishInstructor: "Hafiz Dar",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-48",
    room: "F06",
    level: "Intermediate",
    cohort: "23",
    shift: "PM",
    englishInstructor: "Cornelius Johannes Booyse",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-49",
    room: "F07",
    level: "Intermediate",
    cohort: "23",
    shift: "PM",
    englishInstructor: "Zakaria Hussein",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-50",
    room: "F08",
    level: "Intermediate",
    cohort: "23",
    shift: "PM",
    englishInstructor: "Sorie Gassama",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-51",
    room: "F09",
    level: "PI-S2",
    cohort: "23",
    shift: "PM",
    englishInstructor: "Abdul Rehman Shafique",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-52",
    room: "F38",
    level: "PI-S2",
    cohort: "23",
    shift: "PM",
    englishInstructor: "Abdikarim Hamdi Haji",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-53",
    room: "F12",
    level: "Repeater",
    cohort: "21",
    shift: "PM",
    englishInstructor: "David Seng",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-54",
    room: "F13",
    level: "Repeater",
    cohort: "21",
    shift: "PM",
    englishInstructor: "Qasim Butt",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-55",
    room: "F16",
    level: "Repeater",
    cohort: "21",
    shift: "PM",
    englishInstructor: "Ayyub Yakeen Billah Van Leesten",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-56",
    room: "F17",
    level: "Intermediate",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Ahmed Mahgoub",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-57",
    room: "F41",
    level: "Intermediate",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Nuraddin Egeh",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-58",
    room: "F21",
    level: "Intermediate",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Omer Ahmed Shire",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-59",
    room: "F24",
    level: "Intermediate",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Richard James Schofield",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-60",
    room: "F26",
    level: "Intermediate",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Moegamat Shafiek Allie",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-61",
    room: "F27",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Djibril Samba Thiam",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-62",
    room: "F28",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Abdulrazak Warsame Mohamed",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-63",
    room: "F33",
    level: "Pre-Intermediate",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Jon Joseph Murphy",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-64",
    room: "F34",
    level: "Elementary",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Meddy Kabenge",
    senior: "Hisham Bereir",
  },
  {
    class: "Fnd-65",
    room: "F35",
    level: "Elementary A0",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Mahmud Alhassan Kamal",
    senior: "Asad Mahmood",
  },
  {
    class: "Fnd-66",
    room: "F36",
    level: "Elementary",
    cohort: "24",
    shift: "PM",
    englishInstructor: "Fathi Ibrahim Abdi",
    senior: "Asad Mahmood",
  },
]

